graph_structures:
    graphs:
        -   tag: my-simple-tree
            graph_type: perfect-tree
            graph_options:
                m: 3
                height: 1

        -   tag: my-complex-tree
            graph_type: fractal-tree
            graph_options:
                m: 3
                height: 2

        -   tag: triangle
            graph_type: cycle
            graph_options:
                n: 3

        -   tag: square
            graph_type: cycle
            graph_options:
                n: 4

        -   tag: pentagon
            graph_type: cycle
            graph_options:
                n: 5

        -   tag: tetrahedron
            graph_type: complete
            graph_options:
                n: 4

        -   tag: crossed-box
            graph_type: wheel
            graph_options:
                n: 4

        -   tag: my-simple-walk
            graph_type: walk
            graph_options:
                n: 4

        -   tag: H
            graph_type: custom
            graph_options:
                n_vertices: 6
                edges:
                    - [1, 2]
                    - [2, 3]
                    - [4, 5]
                    - [5, 6]
                    - [2, 5]
                outer_nodes_selection:
                    1: [2]
                    2: [2, 5]
                    4: [1, 3, 4, 6]
                    6: [1, 2, 3, 4, 5, 6]