system:
    python_executable: python3  # Python executable name
    n_python_workers: 12  # Number of Python processes to invoke
    use_cuda: yes  # Use CUDA for GPU acceleration if CUDA is available
    cuda_device: 0  # CUDA device ID to use (0 for the first GPU, 1 for the second, etc.)
    training_allowed: yes  # Allow model to train
    preload_model:
        enabled: no  # Preload a model or initialize a new one
        from: ./export/models/model1.json  # File path to the model file
        error_on_inconsistent_model: no  # Error if the model parameters are inconsistent, otherwise, preload old parameters
        error_on_different_optimization: no  # Error if the optimization parameters are different, otherwise, train with new parameters
    save_checkpoints:
        enabled: yes  # Save model backups frequently
        to: ./output/models/  # Folder path to save checkpoints
        file_name_prefix: ~  # File name prefix for checkpoints ("~" for default value, no prefix)
        frequency: 120  # Delay between checkpoints (seconds)
    log:
        to: ./output/logs/  # Folder path to save logs
        file_name_prefix: ~  # File name prefix for logs ("~" for default value, no prefix)
        n_rotating_logs: 10  # Number of rotating log files
        max_size_per_log: 10  # Maximum size per log files (MB)
        level: low  # Level indicating logging priority (lowest/low/medium/high)
